### ISSUE TITLE
SQLite panics on missing .session_store directory

### ISSUE THREAD

**Issue by mrjoe7** [zaphar/kitchen#25]
```bash
RUST_BACKTRACE=1 cd kitchen && cargo run -- serve
```

will produce error:
```
tomas@home:~/Development/playground/kitchen> RUST_BACKTRACE=1 cargo run -- serve
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/kitchen serve`
2023-01-20T19:50:01.551972Z  INFO kitchen: Launching web interface... listen=127.0.0.1:3030
2023-01-20T19:50:01.555258Z  INFO ui_main{recipe_dir="/home/tomas/Development/playground/kitchen" listen=127.0.0.1:3030}:make_router{recipe_dir="/home/tomas/Development/playground/kitchen"}: kitchen::web::storage: Connecting to sqlite db options=SqliteConnectOptions { filename: "/home/tomas/Development/playground/kitchen/.session_store/store.db", in_memory: false, read_only: false, create_if_missing: true, shared_cache: false, statement_cache_capacity: 100, busy_timeout: 5s, log_settings: LogSettings { statements_level: Info, slow_statements_level: Warn, slow_statements_duration: 1s }, immutable: false, vfs: None, pragmas: {"key": None, "cipher_plaintext_header_size": None, "cipher_salt": None, "kdf_iter": None, "cipher_kdf_algorithm": None, "cipher_use_hmac": None, "cipher_compatibility": None, "cipher_page_size": None, "cipher_hmac_algorithm": None, "page_size": None, "locking_mode": None, "journal_mode": Some("WAL"), "foreign_keys": Some("ON"), "synchronous": None, "auto_vacuum": None}, extensions: {}, command_channel_size: 50, row_channel_size: 50, collations: [], serialized: false, thread_name: Function }
thread 'main' panicked at 'Unable to create app_store: Database(SqliteError { code: 14, message: "unable to open database file" })', kitchen/src/web/mod.rs:555:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::expect
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/core/src/result.rs:1069:23
   4: kitchen::web::make_router::{{closure}}::{{closure}}
             at ./kitchen/src/web/mod.rs:553:9
   5: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   6: kitchen::web::make_router::{{closure}}
             at ./kitchen/src/web/mod.rs:547:1
   7: kitchen::web::ui_main::{{closure}}::{{closure}}
             at ./kitchen/src/web/mod.rs:609:58
   8: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   9: kitchen::web::ui_main::{{closure}}
             at ./kitchen/src/web/mod.rs:607:1
  10: kitchen::main::{{closure}}
             at ./kitchen/src/main.rs:155:81
  11: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/builder.rs:199:17
  12: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/task_locals_wrapper.rs:60:13
  13: std::thread::local::LocalKey<T>::try_with
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/std/src/thread/local.rs:446:16
  14: std::thread::local::LocalKey<T>::with
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/std/src/thread/local.rs:422:9
  15: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/task_locals_wrapper.rs:55:9
  16: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/builder.rs:197:13
  17: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.12.0/src/future.rs:526:33
  18: async_executor::Executor::run::{{closure}}
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.5.0/src/lib.rs:237:31
  19: async_executor::LocalExecutor::run::{{closure}}
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.5.0/src/lib.rs:436:33
  20: async_io::driver::block_on
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.12.0/src/driver.rs:146:33
  21: async_global_executor::reactor::block_on::{{closure}}
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.3.1/src/reactor.rs:3:18
  22: async_global_executor::reactor::block_on
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.3.1/src/reactor.rs:12:5
  23: async_global_executor::executor::block_on::{{closure}}
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.3.1/src/executor.rs:26:36
  24: std::thread::local::LocalKey<T>::try_with
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/std/src/thread/local.rs:446:16
  25: std::thread::local::LocalKey<T>::with
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/std/src/thread/local.rs:422:9
  26: async_global_executor::executor::block_on
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.3.1/src/executor.rs:26:5
  27: async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/builder.rs:171:25
  28: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/task_locals_wrapper.rs:60:13
  29: std::thread::local::LocalKey<T>::try_with
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/std/src/thread/local.rs:446:16
  30: std::thread::local::LocalKey<T>::with
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/std/src/thread/local.rs:422:9
  31: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/task_locals_wrapper.rs:55:9
  32: async_std::task::builder::Builder::blocking::{{closure}}
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/builder.rs:168:17
  33: std::thread::local::LocalKey<T>::try_with
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/std/src/thread/local.rs:446:16
  34: std::thread::local::LocalKey<T>::with
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/std/src/thread/local.rs:422:9
  35: async_std::task::builder::Builder::blocking
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/builder.rs:161:9
  36: async_std::task::block_on::block_on
             at /home/tomas/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.12.0/src/task/block_on.rs:33:5
  37: kitchen::main
             at ./kitchen/src/main.rs:140:9
  38: core::ops::function::FnOnce::call_once
             at /rustc/b569c9dc57ee22b6ff94563af856909763dfa24b/library/core/src/ops/function.rs:507:5
```

**Comment by zaphar** [comment]
Cargo run will also not actually work. you need to run make first. The server embeds the wasm and static assets for the UI so those have to be built first and then copied over. Try running make to get a working server.
